// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/nubunto/autobus-web/design
// --out=$(GOPATH)/src/github.com/nubunto/autobus-web
// --version=v1.1.0-dirty
//
// API "autobus-web": Application Resource Href Factories
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

// GPSHref returns the resource href.
func GPSHref() string {
	return "/gps"
}
